services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vivicity
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

pgadmin:
  image: dpage/pgadmin4:8
  environment:
    PGADMIN_DEFAULT_EMAIL: admin@local.test
    PGADMIN_DEFAULT_PASSWORD: admin
  ports:
    - "5052:80"
  depends_on:
    - db

    
volumes:
  db_data:
